services:
  mysql:
    image: mysql
    container_name: mysql_accenturebank
    environment:
      MYSQL_DATABASE: accenturebank
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  backend: